import { useCallback, useEffect, useState } from "react";
import Card from "../components/Card.jsx";
import Badge from "../components/Badge.jsx";
import { ErrorState, EmptyState } from "../components/StatePanels.jsx";
import { auth } from "../api/client.js";

const EMPTY = { email: "", display_name: "", password: "", role: "mod" };

export default function ModManagementPage() {
  const [users, setUsers] = useState([]); const [form, setForm] = useState(EMPTY); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { setUsers(await auth.users()); setError(""); } catch (err) { setError(err.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); setSaving(true); try { const user = await auth.createUser(form); setUsers((items) => [...items, user]); setForm(EMPTY); setError(""); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const update = async (id, changes) => { try { const user = changes.role ? await auth.updateRole(id, changes.role) : await auth.updateStatus(id, changes.is_active); setUsers((items) => items.map((item) => item.user_id === id ? user : item)); } catch (err) { setError(err.message); } };
  const remove = async (user) => { if (!window.confirm(`Xóa tài khoản ${user.email}? Thao tác này không thể hoàn tác.`)) return; try { await auth.deleteUser(user.user_id); setUsers((items) => items.filter((item) => item.user_id !== user.user_id)); } catch (err) { setError(err.message); } };
  const mods = users.filter((user) => user.role === "mod");
  return <div className="page-grid">
    {error && <div className="page-grid__row"><ErrorState message={error} onRetry={load} /></div>}
    <div className="page-grid__row"><Card title="Tạo tài khoản quản trị" className="span-5"><p className="muted small">Chỉ Admin có thể tạo tài khoản và phân quyền. Mật khẩu được lưu dưới dạng hash.</p><form className="stack-form" onSubmit={create}><label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Tên hiển thị<input required value={form.display_name} onChange={(e) => setForm({ ...form, display_name: e.target.value })} /></label><label>Mật khẩu tạm thời<input required minLength="8" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label>Vai trò<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="mod">Kiểm duyệt viên</option><option value="admin">Quản trị viên</option></select></label><button className="button button--primary" disabled={saving}>{saving ? "Đang tạo…" : "Tạo tài khoản"}</button></form></Card>
      <Card title="Quyền truy cập" className="span-7"><div className="list"><div className="list-row"><strong>Admin</strong><p className="muted small">Quản lý tài khoản, vai trò, nhật kí kiểm duyệt và toàn bộ cấu hình.</p></div><div className="list-row"><strong>Mod</strong><p className="muted small">Thao tác kiểm duyệt được cấp quyền; không thể mở trang hoặc API Nhật kí kiểm duyệt.</p></div></div></Card></div>
    <div className="page-grid__row"><Card title={`Tài khoản Mod (${mods.length})`} className="span-12">{loading && <p className="muted">Đang tải…</p>}{!loading && users.length === 0 && <EmptyState message="Chưa có tài khoản nào." />}{!loading && users.length > 0 && <div className="list">{users.map((user) => <div className="list-row" key={user.user_id}><div className="list-row__head"><div><strong>{user.display_name}</strong><p className="muted small">{user.email}</p></div><div className="chip-row"><Badge tone={user.role === "admin" ? "brand" : "neutral"}>{user.role === "admin" ? "Admin" : "Mod"}</Badge><Badge tone={user.is_active ? "success" : "alert"}>{user.is_active ? "Đang hoạt động" : "Đã khoá"}</Badge>{user.is_root_admin && <Badge tone="brand">Admin gốc</Badge>}</div></div>{!user.is_root_admin && <div className="chip-row"><button className="button button--secondary" onClick={() => update(user.user_id, { role: user.role === "admin" ? "mod" : "admin" })}>Đổi thành {user.role === "admin" ? "Mod" : "Admin"}</button><button className="button button--secondary" onClick={() => update(user.user_id, { is_active: !user.is_active })}>{user.is_active ? "Khoá tài khoản" : "Kích hoạt"}</button><button className="button button--danger" onClick={() => remove(user)}>Xóa tài khoản</button></div>}</div>)}</div>}</Card></div>
  </div>;
}
